version: "3.5"

services:
  elasticsearch:
    container_name: elasticsearch-mongo
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - elastic
  
  kibana:
    container_name: kibana-mongo
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - "5601:5601"
    networks: 
      - elastic
    depends_on:
      - "elasticsearch"
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
      
  apm-server:
    command: --strict.perms=false
    container_name: apm-mongo
    image: docker.elastic.co/apm/apm-server:7.6.2
    ports:
      - "8200:8200"
    networks:
      - elastic
    depends_on:
      - "elasticsearch"
      - "kibana"
    environment:
      - output.elasticsearch.hosts=["localhost:9200"]
    volumes:
      - "./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro"
      
  
networks:
  elastic:
    name: elastic_network
